from setuptools import setup, find_packages

setup(
    name="ocean_analysis",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        'numpy>=1.24.3',
        'pandas>=2.1.3',
        'matplotlib>=3.8.2',
        'seaborn>=0.13.0',
        'cartopy>=0.22.0',
        'pytest>=8.3.4',
        'pytest-asyncio>=0.23.5',
        'tqdm>=4.66.1',
        'langchain>=0.0.335',
        'langchain-community>=0.0.10',
        'python-dotenv>=1.0.0',
        'xarray>=2023.11.0',
        'netCDF4>=1.6.5',
        'gsw>=3.6.17',
        'scikit-learn>=1.3.2',
        'reportlab>=4.0.7',
        'qrcode>=7.4.2',
        'Pillow>=10.1.0',
        'inquirer>=3.1.3',
        'colorama>=0.4.6',
        'scipy>=1.11.4',
        'statsmodels>=0.14.0',
        'plotly>=5.18.0',
        'ipykernel>=6.27.1',
        'jupyter>=1.0.0',
        'notebook>=7.0.6',
        'tavily-python>=0.3.0'
    ],
    python_requires='>=3.8',
    author="Equipo Oceanográfico",
    description="Sistema multiagente para análisis oceanográfico",
    keywords="oceanography, data analysis, multi-agent system",
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Oceanography',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
    ],
) 